pipeline
{
    agent {
  label {
    label 'DevServer'
    retries 2
  }
}
stages {
    stage ('build')
    {
        steps {
            sh 'mvn clean package'
        }
        post {
        success {
            archiveArtifacts artifacts: '**/target/*.war'
            }
        }

    }
}
}
    